/**
 * fullscreenForm.js v1.0.0
 * http://www.codrops.com
 *
 * Licensed under the MIT license.
 * Modified and optimized by Arthur Kirsz
 * 
 */

(function(n){function h(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a}function f(a,b){var d=document.createElement(a);b&&(b.cName&&(d.className=b.cName),b.inner&&(d.innerHTML=b.inner),b.appendTo&&b.appendTo.appendChild(d));return d}function e(a,b){this.el=a;this.options=h({},this.options);h(this.options,b);this._init()}var k=Modernizr.cssanimations,g={WebkitAnimation:"webkitAnimationEnd",OAnimation:"oAnimationEnd",msAnimation:"MSAnimationEnd",animation:"animationend"}[Modernizr.prefixed("animation")];
e.prototype.options={ctrlProgress:!0,ctrlNavDots:!0,ctrlNavPosition:!0,onReview:function(){return!1}};e.prototype._init=function(){this.formEl=this.el.querySelector("form");this.fieldsList=this.formEl.querySelector("ol.fs-fields");this.current=0;this.fields=[].slice.call(this.fieldsList.children);this.fieldsCount=this.fields.length;classie.add(this.fields[this.current],"fs-current");this._addControls();this._addErrorMsg();this._initEvents()};e.prototype._addControls=function(){this.ctrls=f("div",
{cName:"fs-controls",appendTo:this.el});this.ctrlContinue=f("button",{cName:"fs-continue",inner:"Continuer",appendTo:this.ctrls});this._showCtrl(this.ctrlContinue);if(this.options.ctrlNavDots){this.ctrlNav=f("nav",{cName:"fs-nav-dots",appendTo:this.ctrls});for(var a="",b=0;b<this.fieldsCount;++b)a+=b===this.current?'<button class="fs-dot-current"></button>':"<button disabled></button>";this.ctrlNav.innerHTML=a;this._showCtrl(this.ctrlNav);this.ctrlNavDots=[].slice.call(this.ctrlNav.children)}this.options.ctrlNavPosition&&
(this.ctrlFldStatus=f("span",{cName:"fs-numbers",appendTo:this.ctrls}),this.ctrlFldStatusCurr=f("span",{cName:"fs-number-current",inner:Number(this.current+1)}),this.ctrlFldStatus.appendChild(this.ctrlFldStatusCurr),this.ctrlFldStatusTotal=f("span",{cName:"fs-number-total",inner:this.fieldsCount}),this.ctrlFldStatus.appendChild(this.ctrlFldStatusTotal),this._showCtrl(this.ctrlFldStatus));this.options.ctrlProgress&&(this.ctrlProgress=f("div",{cName:"fs-progress",appendTo:this.ctrls}),this._showCtrl(this.ctrlProgress))};
e.prototype._addErrorMsg=function(){this.msgError=f("span",{cName:"fs-message-error",appendTo:this.el})};e.prototype._initEvents=function(){var a=this;this.ctrlContinue.addEventListener("click",function(){a._nextField()});this.options.ctrlNavDots&&this.ctrlNavDots.forEach(function(b,d){b.addEventListener("click",function(){a._showField(d)})});this.fields.forEach(function(b){if(b.hasAttribute("data-input-trigger")){var d=b.querySelector('input[type="radio"]')||b.querySelector("select");if(d)switch(d.tagName.toLowerCase()){case "select":d.addEventListener("change",
function(){a._nextField()});break;case "input":[].slice.call(b.querySelectorAll('input[type="radio"]')).forEach(function(b){b.addEventListener("change",function(b){a._nextField()})})}}});document.addEventListener("keydown",function(b){a.isLastStep||"textarea"===b.target.tagName.toLowerCase()||13!==(b.keyCode||b.which)||(b.preventDefault(),a._nextField())})};e.prototype._nextField=function(a){if(this.isLastStep||!this._validade()||this.isAnimating)return!1;this.isAnimating=!0;this.isLastStep=this.current===
this.fieldsCount-1&&void 0===a?!0:!1;this._clearError();var b=this.fields[this.current];this.navdir=void 0!==a?a<this.current?"prev":"next":"next";this.current=void 0!==a?a:this.current+1;void 0===a&&(this._progress(),this.farthest=this.current);classie.add(this.fieldsList,"fs-display-"+this.navdir);classie.remove(b,"fs-current");classie.add(b,"fs-hide");if(!this.isLastStep){this._updateNav();this._updateFieldNumber();var d=this.fields[this.current];classie.add(d,"fs-current");classie.add(d,"fs-show")}var c=
this,e=function(a){k&&this.removeEventListener(g,e);classie.remove(c.fieldsList,"fs-display-"+c.navdir);classie.remove(b,"fs-hide");c.isLastStep?(c._hideCtrl(c.ctrlNav),c._hideCtrl(c.ctrlProgress),c._hideCtrl(c.ctrlContinue),c._hideCtrl(c.ctrlFldStatus),c._processData(),classie.remove(c.formEl,"fs-form-full"),classie.add(c.formEl,"fs-form-overview"),classie.add(c.formEl,"fs-form-hidden"),c.options.onReview()):(classie.remove(d,"fs-show"),c.options.ctrlNavPosition&&(c.ctrlFldStatusCurr.innerHTML=c.ctrlFldStatusNew.innerHTML,
c.ctrlFldStatus.removeChild(c.ctrlFldStatusNew),classie.remove(c.ctrlFldStatus,"fs-show-"+c.navdir)));c.isAnimating=!1};k?"next"===this.navdir?this.isLastStep?b.querySelector(".fs-anim-upper").addEventListener(g,e):d.querySelector(".fs-anim-lower").addEventListener(g,e):d.querySelector(".fs-anim-upper").addEventListener(g,e):e()};e.prototype._showField=function(a){if(a===this.current||0>a||a>this.fieldsCount-1)return!1;this._nextField(a)};e.prototype._updateFieldNumber=function(){if(this.options.ctrlNavPosition){this.ctrlFldStatusNew=
document.createElement("span");this.ctrlFldStatusNew.className="fs-number-new";this.ctrlFldStatusNew.innerHTML=Number(this.current+1);this.ctrlFldStatus.appendChild(this.ctrlFldStatusNew);var a=this;setTimeout(function(){classie.add(a.ctrlFldStatus,"next"===a.navdir?"fs-show-next":"fs-show-prev")},25)}};e.prototype._progress=function(){this.options.ctrlProgress&&(this.ctrlProgress.style.width=100/this.fieldsCount*this.current+"%")};e.prototype._updateNav=function(){this.options.ctrlNavDots&&(classie.remove(this.ctrlNav.querySelector("button.fs-dot-current"),
"fs-dot-current"),classie.add(this.ctrlNavDots[this.current],"fs-dot-current"),this.ctrlNavDots[this.current].disabled=!1)};e.prototype._showCtrl=function(a){classie.add(a,"fs-show")};e.prototype._hideCtrl=function(a){classie.remove(a,"fs-show")};e.prototype._validade=function(){var a=this.fields[this.current],a=a.querySelector("input[required]")||a.querySelector("textarea[required]")||a.querySelector("select[required]"),b;if(!a)return!0;switch(a.tagName.toLowerCase()){case "input":""===a.value?b=
"NOVAL":isNaN(a.value)?b="NAN":0>a.value&&(b="NEG")}return void 0!=b?(this._showError(b),!1):!0};e.prototype._showError=function(a){var b="";switch(a){case "NOVAL":b="Veuillez renseigner le champ par un nombre avant de continuer";break;case "NEG":b="Les nombres n\u00e9gatifs ne sont pas autoris\u00e9s"}this.msgError.innerHTML=b;this._showCtrl(this.msgError)};e.prototype._clearError=function(){this._hideCtrl(this.msgError)};e.prototype._processData=function(){var a=parseInt(document.querySelector("#q1").value),
b=parseInt(document.querySelector("#q2").value),d=parseInt(document.querySelector("#q3").value),c=.35*parseInt(document.querySelector("#q3").value),e=.85*parseInt(document.querySelector("#q3").value),f=a+b+d+c,a=a+b+d+e,g=parseInt(document.querySelector("#q4").value),h=g-f,k=g-a,l=12*d,m=328.9+14640*.14+.3*(.9*l-26631);document.querySelector("#tns .r1").innerHTML=b+"&nbsp;&euro;";document.querySelector("#tns .r2").innerHTML=d+"&nbsp;&euro;";document.querySelector("#tns .r3").innerHTML=c+"&nbsp;&euro;";
document.querySelector("#tns .r4").innerHTML=f+"&nbsp;&euro;";document.querySelector("#tns .r5").innerHTML=g+"&nbsp;&euro;";document.querySelector("#tns .r6").innerHTML=h+"&nbsp;&euro;";document.querySelector("#tns .r7").innerHTML=l+"&nbsp;&euro;";document.querySelector("#tns .r8").innerHTML=Math.round(m)+"&nbsp;&euro;";document.querySelector("#asa .r1").innerHTML=b+"&nbsp;&euro;";document.querySelector("#asa .r2").innerHTML=d+"&nbsp;&euro;";document.querySelector("#asa .r3").innerHTML=e+"&nbsp;&euro;";
document.querySelector("#asa .r4").innerHTML=a+"&nbsp;&euro;";document.querySelector("#asa .r5").innerHTML=g+"&nbsp;&euro;";document.querySelector("#asa .r6").innerHTML=k+"&nbsp;&euro;";document.querySelector("#asa .r7").innerHTML=l+"&nbsp;&euro;";document.querySelector("#asa .r8").innerHTML=Math.round(m)+"&nbsp;&euro;"};n.FForm=e})(window);